# Generated by Django 4.0.1 on 2022-03-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_location_id_locations_location_id_hints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesses',
            name='guess',
            field=models.TextField(default=''),
        ),
    ]
