# Generated by Django 4.0.1 on 2022-03-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_guesses_guess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guesses',
            options={'verbose_name': 'Guess', 'verbose_name_plural': 'Guesses'},
        ),
        migrations.AlterModelOptions(
            name='hints',
            options={'verbose_name': 'Hint', 'verbose_name_plural': 'Hints'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='words',
            options={'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
    ]
