# Generated by Django 4.0.1 on 2022-03-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_guesses_options_alter_hints_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesses',
            name='guess_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hints',
            name='hint_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='locations',
            name='location_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
