# Generated by Django 4.0.1 on 2022-03-02 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_guesses_user_alter_hints_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesses',
            name='word',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.words'),
        ),
        migrations.AddField(
            model_name='hints',
            name='word',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.words'),
        ),
    ]
