# Generated by Django 4.0.1 on 2022-03-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_hints_hint_code_alter_hints_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hints',
            name='hint_code',
        ),
    ]
