# Generated by Django 4.0.1 on 2022-03-20 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0012_alter_hints_hint_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIns',
            fields=[
                ('checkin_id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('day', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.words')),
            ],
            options={
                'verbose_name': 'Check In',
                'verbose_name_plural': 'Check Ins',
            },
        ),
    ]
