# Generated by Django 4.0.1 on 2022-03-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_checkins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='last_used',
            new_name='date',
        ),
    ]
