# [START django_app]
runtime: python39
entrypoint: gunicorn -b :$PORT main:app
handlers:
# Tel GAE where are Django static assets located
- url: /static
  static_dir: static/
# Route everything else to the main app
- url: /.*
  script: auto
env_variables:
    APPENGINE_URL: https://neural-period-340613.nw.r.appspot.com
# [END django_app]