name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
env:
  SECRET_KEY: django-insecure-(9@fi6ypyq9l&#x@qlpl1*s0bmr@0oyr5-c3vi8ydf+)@l@=n)
  MICROSOFT_AUTH_CLIENT_SECRET: mAG7Q~IwYIJY01RWMLe4V6XWnlp42owM__eh5

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd src
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test
